configuration:  
  projectName: bitmiweb_boot

server:
  port: 8080

sample:
  foo: 'this is foo 입니다.'
  bar: 'this is bar 입니다.'

message:
  greeting: bitmiweb_boot == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR
  
---
spring:
  profiles: dev
  
configuration:  
  projectName: bitmiweb_boot-dev
  
sample:
  foo: 'this is dev-foo 입니다.'
  bar: 'this is dev-bar 입니다. 이건 내가 바꿨지ㅗㅇ~'

message:
  greeting: bitmiweb_boot-dev == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: en_US
  
---
spring:
  profiles: prod

configuration:  
  projectName: bitmiweb_boot-prod
  
sample:
  foo: 'this is prod-foot 입니다.'
  bar: 'this is prod-bar 입니다.'

message:
  greeting: bitmiweb_boot-prod == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR
