#--------------------------------
# project-name
#--------------------------------
configuration:  
  projectName: clemr_boot

#--------------------------------
# server
#--------------------------------
server:
  port: 8080
  display-name: clemr_boot
  session:
    timeout: 1800
    cookie.max-age: 1800
  context-path: /clemr_boot
#  compression:
#    enabled: true
#    min-response-size: 2048
#    mime-types: text/html,application/javascript,image/png,text/xml,application/font-woff

#--------------------------------
# spring
#--------------------------------
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: 'jdbc:log4jdbc:oracle:thin:@122.199.232.165:1521:BITMIHIS'
    username: bitmi0002
    password: bitmiora
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    tomcat:
      url: 'jdbc:log4jdbc:oracle:thin:@122.199.232.165:1521:BITMIHIS'
      username: bitmi0002
      password: bitmiora
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      test-while-idle: true
      test-on-borrow: true
      validation-query: select 'NOT_SQL_LOG' from dual
  redis:
    host: 211.253.29.34
    password: bitcom1983!@#
    port: 6379
  cache:
    cache-names: redis
  session:
    store-type: redis
  context-parameters:
    export-path: file://C:/bitmiweb_boot/workspace/excel
    import-path: file://C:/bitmiweb_boot/workspace/excel
    monitor-enabled: true
    monitor-cycle-time: 30
    file-storage-time: 10
  mvc:
    view:
      prefix: /ipaint/
      suffix: .html
  messages:
    encoding: UTF-8

#  resources:
#    chain:
#      cache: true
#      enabled: true
#    cache-period: 3600
#    static-locations: classpath:/META-INF/resources/,classpath:/public/,classpath:/resources/

#--------------------------------
# etc
#--------------------------------
session:
  expired:
    redirect: /clemr_boot/BITMIWEB/index.html

#--------------------------------
# etc
#--------------------------------
# test message
sample:
  foo: 'this is foo 입니다.'
  bar: 'this is bar 입니다.'

# test message
message:
  locale: ko_KR
  greeting: bitmiweb_boot == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!! !
  
# statics resource location
static:
  resource:
    location: file:///C:/clemrbdata/

# mybatis
mybatis:
  config-location: 'classpath:mybatis-config.xml'
  
# logging
#logging.level.org.springframework.web=INFO
#logging.level.kr.bit.mi.member.dao.MemberDao=DEBUG
#logging.level.kr.bit.mi.common.dao.CodeDao=DEBUG
#logging.level.kr.bit.mi.common.dao.MenuDAO=DEBUG
#logging.level.kr.bit.mi.common.dao.DepartmentDAO=DEBUG
  
#================================
# spring.profiles.active = dev
#================================
---
spring:
  profiles: dev

#--------------------------------
# server
#--------------------------------
server:
  port: 8079
  ssl:
    port: 8443
    key-store: classpath:www.clemr.kr.p12
    key-store-password: bitcom1234
    key-password: bitcom1234
    keyStoreType: PKCS12
    #keyAlias: bitmiweb_boot
    tempFileName: www.clemr.kr
    tempFileExt: .p12
    fileName: www.clemr.kr.p12
    #ciphers: ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA
    #protocol: TLS      
  http:
    port: 8080

#--------------------------------
# etc
#--------------------------------
configuration:  
  projectName: bitmiweb_boot-dev
  
sample:
  foo: ${SPRING_PROFILES_ACTIVE:dev}
  bar: 'this is dev-bar 입니다. 이건 내가 바꿨지ㅗㅇ~'

message:
  greeting: bitmiweb_boot-dev == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR

cypto:
  properties: 'C:\bitmiweb_boot\bin\xecuredb\conf\xdsp_pool.properties'

static:
  resource:
    location: file:///C:/clemrdata/

#================================
# spring.profiles.active = prod
#================================
---
spring:
  profiles: prod

server:
  port: 8079
  ssl:
    port: 8443
    key-store: classpath:www.clemr.kr.p12
    key-store-password: bitcom1234
    key-password: bitcom1234
    keyStoreType: PKCS12
    #keyAlias: bitmiweb_boot
    tempFileName: www.clemr.kr
    tempFileExt: .p12
    fileName: www.clemr.kr.p12
    #ciphers: ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA
    #protocol: TLS      
  http:
    port: 8080
  context-parameters:
    export-path: file://C:/bitmiweb_boot/workspace/excel
    import-path: file://C:/bitmiweb_boot/workspace/excel
    monitor-enabled: true
    monitor-cycle-time: 30
    file-storage-time: 10

configuration:  
  projectName: bitmiweb_boot-prod
  
sample:
  foo: 'this is prod-foot 입니다.'
  bar: 'this is prod-bar 입니다.'

message:
  greeting: bitmiweb_boot-prod == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR

cypto:
  properties: 'C:\bitmiweb_boot\bin\xecuredb\conf\xdsp_pool.properties'

static:
  resource:
    location: file:/clemrdata/

#================================
# spring.profiles.active = test
#================================
---
spring:
  profiles: test

server:
  port: 8079
  ssl:
    port: 8443
    key-store: classpath:www.clemr.kr.p12
    key-store-password: bitcom1234
    key-password: bitcom1234
    keyStoreType: PKCS12
    #keyAlias: bitmiweb_boot
    tempFileName: www.clemr.kr
    tempFileExt: .p12
    fileName: www.clemr.kr.p12
    #ciphers: ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA
    #protocol: TLS      
  http:
    port: 8080
  context-parameters:
    export-path: file://C:/bitmiweb_boot/workspace/excel
    import-path: file://C:/bitmiweb_boot/workspace/excel
    monitor-enabled: true
    monitor-cycle-time: 30
    file-storage-time: 10

configuration:  
  projectName: bitmiweb_boot-test
  
sample:
  foo: 'this is test-foot 입니다.'
  bar: 'this is test-bar 입니다.'

message:
  greeting: bitmiweb_boot-test == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR

cypto:
  properties: 'C:\bitmiweb_boot\bin\xecuredb\conf\xdsp_pool.properties'

static:
  resource:
    location: file:///C:/clemrdata/

#================================
# spring.profiles.active = linux
#================================
---
spring:
  profiles: linux
#  datasource:
#    url: 'jdbc:log4jdbc:oracle:thin:@122.199.232.165:1521:BITMIHIS'
#    username: bitmi0002
#    password: bitmiora
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    tomcat:
#      url: 'jdbc:log4jdbc:oracle:thin:@122.199.232.165:1521:BITMIHIS'
#      username: bitmi0002
#      password: bitmiora
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      test-while-idle: true
#      test-on-borrow: true
#      validation-query: select 'NOT_SQL_LOG' from dual
#  datasource:
#    url: 'jdbc:log4jdbc:oracle:thin:@10.28.8.200:1521:BITMIHIS'
#    username: bitmi0004
#    password: bitmiora
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    tomcat:
#      url: 'jdbc:log4jdbc:oracle:thin:@10.28.8.200:1521:BITMIHIS'
#      username: bitmi0004
#      password: bitmiora
      
server:
  port: 8079
  ssl:
    port: 8443
    key-store: classpath:www.clemr.kr.p12
    key-store-password: bitcom1234
    key-password: bitcom1234
    keyStoreType: PKCS12
    #keyAlias: bitmiweb_boot
    tempFileName: www.clemr.kr
    tempFileExt: .p12
    fileName: www.clemr.kr.p12
    #ciphers: ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA
    #protocol: TLS      
  http:
    port: 8080
  context-parameters:
    export-path: /clemrdata/excel
    import-path: /clemrdata/excel
    monitor-enabled: true
    monitor-cycle-time: 30
    file-storage-time: 10

configuration:  
  projectName: bitmiweb_boot-linux
  
sample:
  foo: 'this is linux-foot 입니다.'
  bar: 'this is linux-bar 입니다.'

message:
  greeting: bitmiweb_boot-linux == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR

cypto:
  properties: '/root/bitmiwebserver/xecuredb/conf/xdsp_pool.properties'

static:
  resource:
    location: file:/clemrdata/

#================================
# spring.profiles.active = ktcloud
#================================
---
spring:
  profiles: ktcloud

server:
  port: 0
  ssl:
    port: 0
    key-store: classpath:www.clemr.kr.p12
    key-store-password: bitcom1234
    key-password: bitcom1234
    keyStoreType: PKCS12
    #keyAlias: bitmiweb_boot
    tempFileName: www.clemr.kr
    tempFileExt: .p12
    fileName: www.clemr.kr.p12
    #ciphers: ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA
    #protocol: TLS      
  http:
    port: 0
  context-parameters:
    export-path: /bitmiwebserver/target
    import-path: /bitmiwebserver/target
    monitor-enabled: true
    monitor-cycle-time: 30
    file-storage-time: 10

configuration:  
  projectName: bitmiweb_boot-ktcloud
  
sample:
  foo: 'this is ktcloud-foot 입니다.'
  bar: 'this is ktcloud-bar 입니다.'

message:
  greeting: bitmiweb_boot-ktcloud == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR

cypto:
  properties: '/root/bitmiwebserver/xecuredb/conf/xdsp_pool.properties'

static:
  resource:
    location: file:/clemrdata/

#================================
# spring.profiles.active = hando
#================================
---
spring:
  profiles: hando
  datasource:
    url: 'jdbc:log4jdbc:oracle:thin:@211.44.250.199:1521:MEPS'
    username: mepsmi
    password: mepsmi!@#123
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    tomcat:
      url: 'jdbc:log4jdbc:oracle:thin:@211.44.250.199:1521:MEPS'
      username: mepsmi
      password: mepsmi!@#123
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      test-while-idle: true
      test-on-borrow: true
      validation-query: select 'NOT_SQL_LOG' from dual
  redis:
    host: 211.253.29.34
    password: bitcom1983!@#
    port: 6380
  cache:
    cache-names: redis
  session:
    store-type: redis

server:
  port: 8079
  ssl:
    port: 8443
    key-store: classpath:www.clemr.kr.p12
    key-store-password: bitcom1234
    key-password: bitcom1234
    keyStoreType: PKCS12
    #keyAlias: bitmiweb_boot
    tempFileName: www.clemr.kr
    tempFileExt: .p12
    fileName: www.clemr.kr.p12
    #ciphers: ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA
    #protocol: TLS      
  http:
    port: 8080
  context-parameters:
    export-path: /
    import-path: /
    monitor-enabled: true
    monitor-cycle-time: 30
    file-storage-time: 10

configuration:  
  projectName: bitmiweb_boot-ktcloud
  
sample:
  foo: 'this is ktcloud-foot 입니다.'
  bar: 'this is ktcloud-bar 입니다.'

message:
  greeting: bitmiweb_boot-ktcloud == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR

cypto:
  properties: 'C:\bitmiweb_boot\bin\xecuredb\conf\xdsp_pool.properties'
  
static:
  resource:
    location: file:///C:/clemrdata/

#================================
# spring.profiles.active = kimes
#================================
---
spring:
  profiles: kimes
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: 'jdbc:log4jdbc:oracle:thin:@122.199.232.175:1521:BITMIHIS'
    username: bitmi0002
    password: bitmiora
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    tomcat:
      url: 'jdbc:log4jdbc:oracle:thin:@122.199.232.175:1521:BITMIHIS'
      username: bitmi0002
      password: bitmiora
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      test-while-idle: true
      test-on-borrow: true
      validation-query: select 'NOT_SQL_LOG' from dual
  redis:
    host: 211.253.29.34
    password: bitcom1983!@#
    port: 6379
  cache:
    cache-names: redis
  session:
    store-type: redis
  context-parameters:
    export-path: file://C:/bitmiweb_boot/workspace/excel
    import-path: file://C:/bitmiweb_boot/workspace/excel
    monitor-enabled: true
    monitor-cycle-time: 30
    file-storage-time: 10
  mvc:
    view:
      prefix: /ipaint/
      suffix: .html
  messages:
    encoding: UTF-8

server:
  port: 8079
  ssl:
    port: 8443
    key-store: classpath:www.clemr.kr.p12
    key-store-password: bitcom1234
    key-password: bitcom1234
    keyStoreType: PKCS12
    #keyAlias: bitmiweb_boot
    tempFileName: www.clemr.kr
    tempFileExt: .p12
    fileName: www.clemr.kr.p12
    #ciphers: ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA
    #protocol: TLS      
  http:
    port: 8080
  context-parameters:
    export-path: file://C:/bitmiweb_boot/workspace/excel
    import-path: file://C:/bitmiweb_boot/workspace/excel
    monitor-enabled: true
    monitor-cycle-time: 30
    file-storage-time: 10

configuration:  
  projectName: bitmiweb_boot-test
  
sample:
  foo: 'this is test-foot 입니다.'
  bar: 'this is test-bar 입니다.'

message:
  greeting: bitmiweb_boot-test == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR

cypto:
  properties: 'C:\bitmiweb_boot\bin\xecuredb\conf\xdsp_pool.properties'

static:
  resource:
    location: file:///C:/clemrdata/
