configuration:  
  projectName: bitmiweb_boot

server:
  port: 8079

sample:
  foo: 'this is foo 입니다.'
  bar: 'this is bar 입니다.'

message:
  greeting: bitmiweb_boot == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR
  
---
spring:
  profiles: dev
  
configuration:  
  projectName: bitmiweb_boot-dev
  
sample:
  foo: ${SPRING_PROFILES_ACTIVE:dev}
  bar: 'this is dev-bar 입니다. 이건 내가 바꿨지ㅗㅇ~'

message:
  greeting: bitmiweb_boot-dev == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR

nhic:
  domain: "ws.nhic.or.kr:1443"
    
cypto:
  properties: 'C:/bitmiweb_boot/bin/xecuredb/conf/xdsp_pool.properties'
    
---
spring:
  profiles: prod

configuration:  
  projectName: bitmiweb_boot-prod
  
sample:
  foo: 'this is prod-foot 입니다.'
  bar: 'this is prod-bar 입니다.'

message:
  greeting: bitmiweb_boot-prod == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR

nhic:
  domain: "ws.nhic.or.kr:1443"
  
cypto:
  properties: 'C:/bitmiweb_boot/bin/xecuredb/conf/xdsp_pool.properties'

---
spring:
  profiles: linux

configuration:  
  projectName: bitmiweb_boot-linux
  
sample:
  foo: 'this is linux-foot 입니다.'
  bar: 'this is linux-bar 입니다.'

message:
  greeting: bitmiweb_boot-linux == 진짜 되네~ ㅋㅋㅋ 와우 진짜인가 봐요~ 안녕하세요? 김강수입니다. 만나서 반갑습니다.!!!!
  locale: ko_KR

nhic:
  domain: "ws.nhic.or.kr:1443"
  
cypto:
  properties: '~/bitmiwebserver/xecuredb/conf/xdsp_pool.properties'
